FROM apify/actor-node-puppeteer-chrome:20
WORKDIR /app
COPY --chown=myuser package*.json .
RUN npm i --omit=dev
RUN mkdir -p /app/storage
RUN chown -R myuser /app/storage
COPY . .
ENV NODE_ENV=production
CMD ["npm", "run", "start"]