FROM apify/actor-node-puppeteer-chrome:20
WORKDIR /app
COPY --chown=myuser package*.json .
RUN npm i
RUN mkdir -p /app/storage_staging
RUN chown -R myuser /app/storage_staging
COPY . .
ENV NODE_ENV=production
ENV PORT=9334
CMD ["npm", "run", "preview"]